apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: three-tier
spec:
  containers:
  - name: backend
    image: 875388088075.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    ports:
    - containerPort: 5000
