apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: three-tier
spec:
  containers:
  - name: frontend
    image: 875388088075.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    ports:
    - containerPort: 80
